name: Cypress API Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Run tests in parallel across two machines
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
          parallel: true
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          